name: cash-book CI
on:
  push:
    paths:
      - '.github/**'
      - 'cash-book**'
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.8.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.8.0

      - name: Install all dependencies
        working-directory: cash-book
        run: yarn

      - name: Run typescript compiler
        working-directory: cash-book
        run: yarn compile

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.8.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.8.0

      - name: Install all dependencies
        working-directory: cash-book
        run: yarn

      - name: Run tests
        working-directory: cash-book
        run: yarn coverage

      - name: Run build
        working-directory: cash-book
        run: yarn build

  integration-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.8.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.8.0

      - name: Install all cash-book dependencies
        working-directory: cash-book
        run: yarn

      - name: Install all cash-book-integration-tests dependencies
        working-directory: cash-book-integration-tests
        run: yarn

      - name: Install Playwright
        working-directory: cash-book-integration-tests
        run: npx playwright install --with-deps

      - name: Run integration tests
        working-directory: cash-book-integration-tests
        run: npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: cash-book-integration-tests/playwright-report/
          retention-days: 30
